### ISSUE TITLE
nodejs, http-parser deps

### ISSUE THREAD

**Issue by asquelt** [helber/fedora-specs#1]
which repo do you use for above dependencies?

**Comment by helber** [comment]
All dependencies i use default fedora repos.
But npm need to be updated, and i use npm itself to update, using:

> "npm install -g --ca=null --prefix %{buildroot}/usr npm@2.7.6"

The gyp also need to be updated, and i clone from:

> git clone https://chromium.googlesource.com/external/gyp

**Comment by asquelt** [comment]
it seems to work with epel and centos, thank you.

**Comment by helber** [comment]
Just to know i am creating atom to centos, epel, fedora 21,22,23 on my copr:
https://copr.fedoraproject.org/coprs/helber/atom/
